name: Hako Test
on: [push, pull_request]
jobs:
  test:
    name: Hako Test
    runs-on: ubuntu-latest
    steps:
      - name: Initialize
        uses: ./.github/actions/base
      - name: Test
        run: composer test
