name: Hako Test
on: [pull_request]
jobs:
  test:
    name: Hako Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Initialize
        uses: ./.github/actions/base
      - name: Test
        run: composer test
