name: Hako Test
on: [push, pull_request]
jobs:
  test:
    name: Hako Test
    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1"
      - name: Checkout
      - uses: actions/checkout@v3
      - name: Validate Composer Packages
        run: composer validate
      - name: Cache Composer Packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-
      - name: Install Composer
        run: composer install
      - name: Test
        run: composer test
